// <auto-generated />
namespace Aanwezigheidslijst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newdlnmrdocDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdlnmrdocDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201907221418547_new dlnmr & doc DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
